spring:
  security:
    user:
      name: ${SPRING_USERNAME}
      password: ${SPRING_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/sleep
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/sleep
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
server:
  error:
    include-exception: true
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

