CREATE TABLE sleep_info_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sleep_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   get_up_date_time TIMESTAMP WITHOUT TIME ZONE,
   hours BIGINT,
   CONSTRAINT pk_sleep_info_entries PRIMARY KEY (id)
);